# Generated by Django 3.1.5 on 2021-01-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True, verbose_name='SYMBOL')),
                ('name', models.CharField(max_length=100, verbose_name='NAME')),
                ('price', models.CharField(max_length=50, verbose_name='PRICE')),
                ('open', models.CharField(max_length=50, verbose_name='OPEN')),
                ('day_min', models.CharField(max_length=50, verbose_name='DAY_MIN')),
                ('day_max', models.CharField(max_length=50, verbose_name='DAY_MAX')),
                ('volume', models.CharField(max_length=50, verbose_name='VOLUME')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
            ],
        ),
    ]
